### ISSUE TITLE
MATERIALES PARA UTILIZAR 

### ISSUE THREAD

**Issue by JonatanR97** [JonatanR97/Proyecto_Analisis_De_Sistemas#10]

**Comment by JonatanR97** [comment]
[MATERIALES MAQUINA DISPENSADORA.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6557877/MATERIALES.MAQUINA.DISPENSADORA.docx)

**Comment by fred001-lop** [comment]
[MATERIALES MAQUINA DISPENSADORA.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6564110/MATERIALES.MAQUINA.DISPENSADORA.docx)
