### ISSUE TITLE
1RA. ETAPA MAQUINA DISPENSADORA 

### ISSUE THREAD

**Issue by JonatanR97** [JonatanR97/Proyecto_Analisis_De_Sistemas#12]

**Comment by JonatanR97** [comment]
[1RA.ETAPA ANALISIS DEL PROYECTO.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6527321/1RA.ETAPA.ANALISIS.DEL.PROYECTO.docx)

**Comment by JonatanR97** [comment]
SE NECESITA QUE SE SUBA LA PARTE CORRESPONDIENTE A ESTA TAREA

**Comment by fred001-lop** [comment]
[Etapa 1 Máquina Dispensadora de Bebidas.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6564103/Etapa.1.Maquina.Dispensadora.de.Bebidas.docx)
