### ISSUE TITLE
2DA. ETAPA MAQUINA DISPENSADORA 

### ISSUE THREAD

**Issue by JonatanR97** [JonatanR97/Proyecto_Analisis_De_Sistemas#13]

**Comment by fred001-lop** [comment]
[Etapa 2 Máquina Dispensadora de Bebidas.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6564117/Etapa.2.Maquina.Dispensadora.de.Bebidas.docx)
