### ISSUE TITLE
FASE FINAL DEL PROTOTIPO

### ISSUE THREAD

**Issue by JonatanR97** [JonatanR97/Proyecto_Analisis_De_Sistemas#20]

**Comment by JonatanR97** [comment]
[FaseFinal.docx](https://github.com/JonatanR97/Proyecto_Analisis_De_Sistemas/files/6565328/FaseFinal.docx)

**Comment by fred001-lop** [comment]
![Finalizado](https://user-images.githubusercontent.com/84173416/120255211-abc23f00-c248-11eb-91a3-da15205e1385.png)
![Finalizado2](https://user-images.githubusercontent.com/84173416/120255213-ac5ad580-c248-11eb-83c7-81cb9e194ed3.PNG)
