### ISSUE TITLE
Fallas del Proyecto

### ISSUE THREAD

**Issue by JonatanR97** [JonatanR97/Proyecto_Analisis_De_Sistemas#23]

**Comment by JonatanR97** [comment]
![WhatsApp Image 2021-05-29 at 12 13 42 AM (1)](https://user-images.githubusercontent.com/73360698/120254849-f7c0b400-c247-11eb-8ed0-add449bcae9d.jpeg)

**Comment by JonatanR97** [comment]
![2 (2)](https://user-images.githubusercontent.com/73360698/120254886-0d35de00-c248-11eb-9922-3ad838cbbae5.PNG)

**Comment by JonatanR97** [comment]
![1 (2)](https://user-images.githubusercontent.com/73360698/120254905-18890980-c248-11eb-9431-036e933a81e2.PNG)

**Comment by fred001-lop** [comment]
![2 (2)](https://user-images.githubusercontent.com/84173416/120255092-7584bf80-c248-11eb-8660-9e7612e09af9.PNG)
![1 (2)](https://user-images.githubusercontent.com/84173416/120255094-7584bf80-c248-11eb-9b8d-17786256053a.PNG)
![WhatsApp Image 2021-05-29 at 12 13 52 AM](https://user-images.githubusercontent.com/84173416/120255102-7b7aa080-c248-11eb-87b6-79e9f55e9832.jpeg)
![WhatsApp Image 2021-05-29 at 12 13 42 AM (1)](https://user-images.githubusercontent.com/84173416/120255107-7ddcfa80-c248-11eb-9cdf-8a84401e001b.jpeg)
![WhatsApp Image 2021-05-29 at 12 13 42 AM](https://user-images.githubusercontent.com/84173416/120255120-80d7eb00-c248-11eb-99fc-d594d0b79451.jpeg)
